### ISSUE TITLE
results size wrongly reported as 50 for large single word indexes

### ISSUE THREAD

**Issue by coolmeen** [RedisLabsModules/RediSearch#12]
hi.
i tried to insert a simple one fielded text to and index and then query it.
i inserted the word "hello' for multiple times.
everything was ok until the 5000 insertion but when i inserted the 5001 document the the search result for the world "hello" returned a constant result of 50 appearances , instead of 5001 appearances.

thx all

**Comment by dvirsky** [comment]
there's no real problem - just the number reported is wrong. for long indexes we **additionally** save an optimized version of the index that includes just the top 50 documents, instead of traversing the entire index when you just want that word. The 50 results reported are a bug, but you can safely ignore it and page beyond 50 results, I've used the index with over 5,000,000 documents easily. I'm changing the issue title.

**Comment by dvirsky** [comment]
Also note that this only applies to single word queries.

**Comment by dvirsky** [comment]
Fixed (in master and release 0.2.1)
