### ISSUE TITLE
How to search and index arrays.

### ISSUE THREAD

**Issue by kilianc** [RedisLabsModules/RediSearch#183]
This is what I am doing at the moment, `NOSTEM` and joining the array like this 

```
`#${tags.join('#')}#`
```

```js
exports.matchArray = (fieldName, values) => {
  return `@${fieldName}:${values.map((s) => `"#${s}#"`).join(' ')}`
}
```

I am till working on the implementation, but even if this works, is there a better way?

**Comment by dvirsky** [comment]
I'm working on a special type of "tag index" that also consumes less memory since it needs to store less info per entry than a full text field. You'll be able to tell the index what your separators are and it will not do any tokenization or stemming beyond that.

However until it's ready your approach sounds ok, I'd replace spaces with underscores (they do not get separated in tokenization), and it will work. i.e if my tags are `hello world, foo bar` I'd convert it into `hello_world foo_bar`. A comma will also serve as a separator of course.

**Comment by kilianc** [comment]
thanks @dvirsky , our use case is just tokens and hashtags so that shouldn't be necessary. thanks for doing some sanity checking with me :)

**Comment by dvirsky** [comment]
@kilianc I'm closing this issue, then? 

Also, if this is the only use you are making of RediSearch and you're not interested in proximity or exact match searches, create the index with NOOFFSETS and you'll save tons of memory. The offset vectors are used to match terms in order and proximity, but if you're just looking at tokens they are redundant. And they usually take up most of the RAM in the index.
