### ISSUE TITLE
Results order question - exact match at the bottom

### ISSUE THREAD

**Issue by kilianc** [RedisLabsModules/RediSearch#189]
This is more of a question than a bug report probably.

Searching for `@text:foo` will return:

```
this is foo ok?
hello foo
foo!
foo
```

Which feels like the result set is upside down. Is this expected behavior?

**Comment by salt4pommes** [comment]
FT.CREATE test SCHEMA text TEXT WEIGHT 1.0
ft.add test 1 1.0 FIELDS text "this is foo ok?"
ft.add test 2 1.0 FIELDS text "foo!"
ft.add test 3 1.0 FIELDS text "foo"
ft.add test 4 1.0 FIELDS text "Hello foo"

My results when using "ft.search test @text:foo" or ft.search test foo are:

Hello foo
foo

**Comment by dvirsky** [comment]
A few things to note:
1. If result scores are exactly the same, we order by internal incremental docId, which is basically creation order. 
2. The term frequency in the TF-IDF scorer is normalized to the most frequent term in the document, so in this case the TF of all results is the same. Also the IDF is irrelevant since it's just one word.

The default algorithm is as follows: for each result, the score is the a priory document score, multiplied by the sum of the TF-IDF of all the matching words. the TF is as I said above, optionally where each field is weighted - and normalized by most frequent token in the document. 

On multi word queries, we apply an extra step, and reduce the score by the accumulated distance between the terms, squared. So if I have two results for `foo bar` that happen to be identical in score, and in one the match is "foo bar"  and in the other the match is "foo woop woop bar" - the second one will have a distance penalty factor of 1/2^2, or 0.25. 

Optionally, you can choose a much simpler scoring function by adding `scorer DISMAX`, that put simplistically, sums up the frequencies. It's also way faster for very big result sets.

I need to expand this explanation to a proper documentation doc.

**Comment by kilianc** [comment]
@dvirsky thanks for taking the time to explain. That makes complete sense now.

I have one question still, shouldn't "foo bar" get the *distance penalty* when searching for "foo" in order to get "foo" at the top of the result set?

I don't think this is related to just *one-worders* BTW I can provide other cases when with 4 or 5 words queries where the exact match is in the middle of the results or at the bottom. While it makes sense with your explanation why that would happen it still doesn't feel right.

This said I understand the design decision, I just wanted to see if there is room for *improvement* or adjustment :)

Thanks

**Comment by dvirsky** [comment]
What you are saying is that the relative frequency of the term should be normalized a bit differently, not necessarily by the most frequent token, but also taking into account the document size. This causes small documents to rise to the top of results. 
There are several ways of normalizing term frequencies, which will  and a slightly more modern alternative to TF-IDF called BM25, you can look them up on Wikipedia. 

I don't mind adding BM25 as another optional scorer built-in. The cool thing is that you can write your own algorithm if you want, the frequencies and scores are exposed via the extension API.

**Comment by kilianc** [comment]
I need to educate myself a little bit more before giving more feedback. Thanks for the references 👍

**Comment by kilianc** [comment]
I after reviewing some of the literature about BM25 I think it would suit our use case better than IDTF.

@dvirsky do you see this landing in the next week or so?

**Comment by dvirsky** [comment]
I'm keeping this open until we implement BM25, hopefully next week.

**Comment by dvirsky** [comment]
BM25 added to master along with a few other scorers, and proper documentation on them: redisearch.io/Scoring/
