### ISSUE TITLE
INORDER giving inconsistent results

### ISSUE THREAD

**Issue by arora-kushal** [RedisLabsModules/RediSearch#213]
If we are using INORDER in a query, it searches for "query terms" in same order AS WELL AS columns to be in same order. However, it should only consider "query terms" in same order, regardless of columns in the search query.

Schema:
FT.CREATE VVVV schema Col_1 Text Sortable Col_2 Text Sortable
FT.ADD VVVV K1 1 FIELDS Col_1 "hello world" Col_2 "Lorem Ipsum is simply dummy text of the printing and typesetting industry"

The following query is working as expected:
FT.SEARCH VVVV "@Col_1:(hello world) @Col_2:(typesetting industry)"  INORDER NOCONTENT
1) (integer) 1
2) "K1"

However, following search query is not returning any results:

FT.SEARCH VVVV "@Col_2:(typesetting industry) @Col_1:(hello world)" INORDER NOCONTENT
1) (integer) 0

**Comment by dvirsky** [comment]
This is actually consistent. The ordering is enforced across the entire query. The second query is not, in fact, in order. the order of the sub phrases in the query is reversed. See #212 for the way we'd like to make these enforcements optionally per sub-query. But this is the expected behaviour at the moment.
