### ISSUE TITLE
Can't install redis-server with search module

### ISSUE THREAD

**Issue by eitanshapiro** [RedisLabsModules/RediSearch#22]
Need the option to install redis-server 4.0 RCe and specify the search module for the executable.

**Comment by dvirsky** [comment]
Please explain what you mean.

**Comment by mheiber** [comment]
@eitanshapiro not sure what your issue is, but maybe this will help:

1. clone this repo
1. `cd src`
1. `make`
1. add the path to `module.so` to your `redis.conf`. For example, my `redis.conf` looks like this: `loadmodule /Users/mheiber/dev/RediSearch/src/module.so`
1. restart redis-server. On startup, it should say "Module 'ft' loaded"

**Comment by dvirsky** [comment]
@eitanshapiro care to elaborate on this? or shall I close it?

what behavior do you imagine?

**Comment by eitanshapiro** [comment]
Adding the module to the config helped. Thx.

**Comment by mheiber** [comment]
In case anyone lands here in the future, see the [RediSearch Quick Start](http://redisearch.io/Quick_Start/).
