### ISSUE TITLE
FT.SEARCH with fuzzy

### ISSUE THREAD

**Issue by martinmakesitwork** [RedisLabsModules/RediSearch#251]
Hi everyone,

is there a way to use FT.SEARCH with kind of fuzzy search? 
My first try was to use autocomplete, but this doesnt work for me, because i need to have duplicate values with different payloads.

At the moment my search looks like that:
 `'FT.SEARCH',
                [ 'searchlist', searchstring + '*', 'SORTBY', 'someAttribute', 'DESC' ]`

I thank you a lot for every help!

**Comment by dvirsky** [comment]
Hi. Fuzzy search is supported only on completion. But since we do support it in the actual algorithm, it's just an API detail to add this. We'll try to get to it soon!

**Comment by martinmakesitwork** [comment]
Do you think it will come in the closer next time?
That would be absolutly great!

Thank you for your great help!

**Comment by dvirsky** [comment]
I'll put it in the TODO since it's not a lot of work, the algorithm actually exists. I mostly need a way to express it in the query syntax. 

Suggestions are welcome! Ideas:

```
*fuzzy* 
%fuzzy%
~fuzzy~
```
I think the percentage is the best option since it doesn't have other meanings in the syntax. Down side: it doesn't mean what it means in SQL LIKE queries, which I'm certain will cause confusion.

**Comment by dvirsky** [comment]
added in 1.2.0
