### ISSUE TITLE
compilation error on Alpine: qsort_r

### ISSUE THREAD

**Issue by raulggonzalez** [RedisLabsModules/RediSearch#260]
When compiling on **Alpine**, the following error is received:

```
redis[~/RediSearch/src]$ make all
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/home/redis/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API  -g -ggdb -O3    -c /home/redis/RediSearch/src/fragmenter.c -o /home/redis/RediSearch/src/fragmenter.o -MMD -MF /home/redis/RediSearch/src/fragmenter.d
/home/redis/RediSearch/src/fragmenter.c: In function 'FragmentList_Sort':
/home/redis/RediSearch/src/fragmenter.c:14:54: error: implicit declaration of function 'qsort_r' [-Werror=implicit-function-declaration]
 #define myQsort_r(arr, nelem, elemSize, compfn, arg) qsort_r(arr, nelem, elemSize, compfn, arg)
                                                      ^
/home/redis/RediSearch/src/fragmenter.c:267:3: note: in expansion of macro 'myQsort_r'
   myQsort_r(fragList->sortedFrags, fragList->numFrags, sizeof fragList->sortedFrags[0], fragSortCmp,
   ^~~~~~~~~
cc1: some warnings being treated as errors
make: *** [Makefile:73: /home/redis/RediSearch/src/fragmenter.o] Error 1
redis[~/RediSearch/src]$
```

Environment info:

```
redis[~/RediSearch/src]$ apk info | sort
alpine-baselayout
alpine-keys
apk-tools
bash
binutils
binutils-libs
build-base
busybox
ca-certificates
expat
fortify-headers
g++
gcc
git
gmp
isl
libatomic
libc-dev
libc-utils
libcurl
libgcc
libgomp
libressl2.5-libcrypto
libressl2.5-libssl
libssh2
libstdc++
make
mpc1
mpfr3
musl
musl-dev
musl-utils
ncurses-libs
ncurses-terminfo
ncurses-terminfo-base
pcre
pkgconf
readline
scanelf
su-exec
zlib
redis[~/RediSearch/src]$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.2
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
redis[~/RediSearch/src]$
```

**Comment by dvirsky** [comment]
That's odd, according to the man page, `-D_GNU_SOURCE` should take care of that, but perhaps there's a missing include. @mnunberg ?

**Comment by mnunberg** [comment]
What is Alpine Linux based off? and yes, _GNU_SOURCE should avoid this; unless there's some header somewhere explicitly turning it off?

Maybe try -D_GNU_SOURCE=1 - it could be that it's looking for an `#if` instead of `#ifdef`? Or define it at the top of the file and include stdlib.h individually? --

If I can get an env that does this for me already, it'd be easier :)

**Comment by dvirsky** [comment]
@mnunberg https://en.wikipedia.org/wiki/Alpine_Linux

It's a minimalist distro used mostly for containers. I tried originally basing our docker image on it, but eventually went on with building on Debian. You can just change the docker file a bit to try and build it on Alpine (just don't commit)

**Comment by raulggonzalez** [comment]
FYI: I'm using redis:4-alpine image.

**Comment by mnunberg** [comment]
0c341a387cfa7a9aa8bd335d774d9be915e5ed71 and the prior commit should fix this issue. I've eliminated the need for using `qsort_r` and simplified the code there a bit more. I don't believe there should be any different in performance.

Previously the indexes were sorted separate from the fragments themselves; we maintain this, but instead of indexes, use actual pointers instead.
