### ISSUE TITLE
Tag fields do not work over AOF

### ISSUE THREAD

**Issue by tw-bert** [RedisLabsModules/RediSearch#283]
Queries with Tag fields are not working after BGREWRITEAOF and loading this AOF file.  
Furthermore, tag hashes are not dropped at a FT.DROP (at the recreated redis instance).  
FT.CREATE should check for conflicting tag hash key names.

**Comment by mnunberg** [comment]
I've got this one - was requested via #282

**Comment by mnunberg** [comment]
I've decided to not do this verification in `FT.CREATE` since the presence of an existing tag hash key name would be an internal bug rather than a user error (unless someone is particularly crafty) -- in which case we should verify that things like this do not occur in general (i.e. someone trying to masquerade keys as RS objects).

**Comment by tw-bert** [comment]
@dvirsky @mnunberg : I agree that a conflicting tag hash is unlikely to be present on a happy path. But, if it happens to be there (from an internal bug, or from an incomplete manual failover scenario that has nothing to do with FT), the internal bug is completely obfuscated. We just saw very strange results, and started debugging the query parser, and then questioning the intersect/join logic, until we saw that the results on tags were wrong. And at that point, we didn't even know the cause of that. My 2 cents.

**Comment by mnunberg** [comment]
@dvirsky seems like a general improvement to the 'hardening' checklist. Should we add this one specific fix here though?

**Comment by tw-bert** [comment]
@mnunberg :
> We're still going through potential AOF bugs, so brace yourself!

But... I can test the latest master for the "tag sort" and "tag drop at ft.drop" issues?

**Comment by dvirsky** [comment]
@mnunberg long term we want to fold the entire index into a single key, right? In that case all that crap can be avoided. For now we can just verify on index creation that there doesn't exist a key of another type under that name.

**Comment by tw-bert** [comment]
@dvirsky @mnunberg Fix works fine! Is it possible to do a bugfix release for https://github.com/RedisLabsModules/RediSearch/issues/283 & https://github.com/RedisLabsModules/RediSearch/issues/282 ?

(_FT.CREATE should check for conflicting tag hash key names._) -> dismissed

**Comment by dvirsky** [comment]
@tw-bert we've found a couple of important stability bugs in recent days and we'll release a bugfix version today or tomorrow with all this stuff. 

BTW are you using WITHSORTKEYS when sorting by sortable fields?

**Comment by tw-bert** [comment]
@dvirsky Great!

> BTW are you using WITHSORTKEYS when sorting by sortable fields?

No, not in production. The WITHSORTKEYS mentioned in the previous issue was only for debugging.

**Comment by dvirsky** [comment]
great, because I'm going to change the API a bit. 
We have a problem in the distributed version (which is the reason WITHSORTKEYS even exists). Until now it tried to just parse the sorting key as a number and if it is, we compare records numerically. This resulted in weird results if a TEXT field contains numbers. The nodes sort alphabetically and the coordinator sorts numerically. 

So now string sorting keys will have `$` prepended to them, and numbers will have `#`, and the coordinator will be strict about how it parses the values. 

I doubt anyone is using this option but us, and anyway it will not change the sorting order of strings.

**Comment by tw-bert** [comment]
@dvirsky Clear, thx for the additional info
