### ISSUE TITLE
NUMERIC sortkeys are lost after restore from AOF

### ISSUE THREAD

**Issue by tw-bert** [RedisLabsModules/RediSearch#288]
Redis `4.0.8`, RediSearch `1.0.7`

This issue is a follow-up on https://github.com/RedisLabsModules/RediSearch/issues/282 (which solves an almost identical issue, but apparently only on `TEXT` sortable fields)

After restore from AOF, sorting on NUMERIC does not work anymore, as the sortkeys are not restored.

Simple to reproduce:
```lisp
ft.create idx schema foo numeric sortable bar tag
ft.add idx 1 1 fields foo 1 bar 1
ft.add idx 2 1 fields foo 2 bar 1
bgrewriteaof
debug loadaof
ft.search idx '@bar:{1}' sortby foo asc return 1 foo withsortkeys
--> Results below are in the wrong order [reason: the sortkeys should not be (nil)]
1) (integer) 2
2) "2"
3) (nil)
4) 1) "foo"
   2) "2"
5) "1"
6) (nil)
7) 1) "foo"
   2) "1"
```

We can work around this issue by:
1. drop all our FT indexes with NUMERIC sortkeys
2. recreate these FT indexes
3. repopulate these indexes (our custom scripts)

**Comment by dvirsky** [comment]
@tw-bert I'm considering abolishing AOF only mode in RediSearch, and would like to hear your take. In redis 4.0 it is a little known fact that you can use a hybrid model of persistence, where instead of AOF rewriting, you get an RDB dump, and that dump is appended AOF records until the next compaction cycle. 

This removes all the complications of persisting the indexes to AOF, while letting you keep the same consistency and safety guarantees. Right now keeping the two modes is painful and as you can see error prone. I think we should simply not allow "classic" AOF mode anymore, only the new kind.

Thoughts?

**Comment by tw-bert** [comment]
@dvirsky I can understand that two persistency models is hard to maintain. I do however strongly disagree with abolishing AOF, for several reasons. 

I'm well aware of the hybrid AOF mode, but that will not remove your problem. It will only remove your problem inside the RDB part of the AOF file, and will render the actual AOF state (all changes on top of the RDB part) invalid.

Salvatore has a nice summary here: https://redis.io/topics/persistence , which you are probably well aware of.

For our usecases (and most probably others), AOF is much more valuable than RDB. More than that: it is a necessity. We can't do a snapshot each second, or even each minute, on a 7GB dataset (which will definitely grow in the next few years). And we do need that level of backup granularity, because of business requirements.

AOF is also far more elegant imo, and makes the server's performance far more consistent, without any peeks (except for the occasional rewrite, which can be planned). 
When we started out with Redis, we used both, but are now AOF-only on the master side (configured to use diskless replication, which does stream RDB format to slaves, but causes no stress on our file servers).

I might even go a step further: if you plan to ditch one of the two, ditch RDB (at the redis core as well). But keep the possibility of a compressed and speed optimized snapshot preample inside the AOF (RDB format or not). Which in summary, might not reduce the amount of work RediSearch has to put into two different persistency mechanisms (it is still snapshotting + append-only).

I do think you are almost there though... this might be the last issue and seems very similar to the TEXT sortkeys one.

**Comment by dvirsky** [comment]
>  We can't do a snapshot each second, or even each minute, on a 7GB dataset (which will definitely grow in the next few years). And we do need that level of backup granularity, because of business requirements.

The hybrid model will not hurt that. 

Doing AOF proper is easy - you just replicate the commands as they come to the file.

The problem is rewriting the AOF for compaction, not keeping it at all. We have to provide redis with ways to persist keys into rewritten AOF files, even though no commands are present to create these keys besides indexing documents. This makes use invent special contrived commands that are only used in this context and are very fragile. Moreover, since we support indexing without actually saving the documents, this only makes it further complicated. Also, since AOF strings can be 512MB at most IIRC, rewriting some very big keys is broken inherently, it's just a wall that hasn't been hit by anyone. 

The AOF rewrite model is really bad for an index. So the hybrid model will not in any way hurt your durability - as long as you don't compact your AOFs they are still there and can be read from. But the horrible AOF rewrite thing will go away forever. It's a win win for me. 

We'll never ditch RDB, that is certain.

**Comment by tw-bert** [comment]
@dvirsky Ah, now I see your point. Let me think this over, I might agree.

**Comment by tw-bert** [comment]
@dvirsky Yes, I fully agree now. Thanks a lot (why didn't *we* think of that ;) ).

I just tested this with our auxilary AOF per-second archive, and no problems there.
After discussing the config change with our sysadmin team (and testing on dev), we already switched one of our live servers as well:

```bash
config set aof-use-rdb-preamble yes
bgrewrite
```

This immediately solves our problems.

We have no reason to go back, so if you want to ditch all AOF rewrite code, please do. You might consider a hardening check at first FT-write: if `appendonly==yes` and `aof-use-rdb-preamble==no` then `raise(No go!)`.

**Comment by dvirsky** [comment]
Cool, I'm glad you're on board with the change.

@mnunberg let's discuss closing aof only mode, it should be a very small
change (apart from removing a shitload of code and some tests), but we
should communicate it properly and test it thoroughly on the enterprise
version (this shouldn't pose a problem but needs some testing).

We can do it with the next minor version (1.1.0) which will include
aggregations and some rather big changes.

**Comment by tw-bert** [comment]
Hint on terminology : "aof only mode" is a bit ambiguous. It is still fine to use both AOF and RDB at the same time. Maybe "AOF rdb-preamble setting mandatory"?

Only mentioning this because it caused some confusion on our side.
