### ISSUE TITLE
issue with incomplete word

### ISSUE THREAD

**Issue by tuananh** [RedisLabsModules/RediSearch#339]
```
FT.CREATE myIdx SCHEMA name TEXT
FT.ADD myIdx doc1 1.0 FIELDS name "record 1"
FT.ADD myIdx doc2 1.0 FIELDS name "record 10"
```

However this command doesn't show any result

```
FT.SEARCH myIdx "record 1*" WITHSCORES INORDER VERBATIM SCORER BM25
```

Without the `*`, it works as expected.

Is this expected behavior?

How can i make it work with query like `record 1*` ?

**Comment by tuananh** [comment]
hm, the issue is there only if the last word is 1 char length

**Comment by itamarhaber** [comment]
Hello @tuananh,

Interesting find, definitely not the expected behavior AFAICT. Thanks for reporting :)

**Comment by mnunberg** [comment]
This is not a bug but is by design, and documented. Basically, a prefix query forms a logical union query, and if prefixes are too small, the union might end up becoming too big, dramatically slowing the query.

You can change `MINPREFIX` when loading the module to `1` in order to make all prefixes work (but beware of the implications if you have a lot of terms and do a query with `i*` for example).

**Comment by itamarhaber** [comment]
I learn something new every day, and in this case I need to RTFM :) Funnily enough, I'm currently fixing typos in configuration.md.

**Comment by tuananh** [comment]
Ah make sense. Thanks

**Comment by tuananh** [comment]
@mnunberg  what about this case? I'm not using prefix search 

```
FT.CREATE myIdx SCHEMA name TEXT
FT.ADD myIdx doc1 1.0 FIELDS name "ha noi"
FT.ADD myIdx doc2 1.0 FIELDS name "ha nam"

FT.SEARCH myIdx "ha n" WITHSCORES WITHPAYLOADS INORDER VERBATIM SCORER BM25 limit 5
```
