### ISSUE TITLE
make->Cmake (1.0.4) small issues

### ISSUE THREAD

**Issue by tw-bert** [RedisLabsModules/RediSearch#487]
Hi @mnunberg,

1. At the [Quick Start](https://oss.redislabs.com/redisearch/Quick_Start/#building%22_%22and%22_%22running%22_%22from%22_%22source), the output is `./src/redisearch.so`. I think that has changed to `./redisearch.so`
2. Our sysadmin prefers to use the [RediSearch GitHub Releases Page](https://github.com/RedisLabsModules/RediSearch/releases) , downloading the jar.gz with `wget`. Since the jar file is not a git repository, he needed to modify `Makefile` and `CMakeLists.txt`. Is it possible to do a cmake+make without a repo? I did notice the `GIT_DESCRIBE_VERSION` but am not that familiar with cmake.
3. Is the version number in `MODULE LIST` correct? It returns `10300` for our `1.0.4` build.

**Comment by mnunberg** [comment]
I recall we switched to a new versioning scheme recently, but I'm not sure if the 1.3.0 in the version number is a feature or a bug :)

If you're using CMake properly, the output should be in `./build/redisearch.so` - or whatever your build directory is. The intention was to have the Makefile wrap CMake with a regular `make` so that pre-cmake users can still use it and mostly not see any difference.

I've just tried to download the release tarball from the releases page, and simply run `make`. There is a `src/redisearch.so` as before, and I didn't need to do anything other than run `make`. It shows a "fatal" message, but that message is from Git itself (i.e. git dying because it's not a repo). The build can certainly continue.

It'll fail of course, if you don't have cmake.

**Comment by mnunberg** [comment]
@tw-bert Can we close this?

**Comment by tw-bert** [comment]
@mnunberg Sorry for the delay - hectic week.

I can confirm that, if `cmake` is installed, `make` runs fine on the release. I must have been confused with the cmake dependency, which wasn't installed at first. 

The documentation is also correct. I'll close this issue + thx for the feedback.
