### ISSUE TITLE
Field search with multiple words

### ISSUE THREAD

**Issue by mahemoff** [RedisLabsModules/RediSearch#528]
According to docs, this should be possible:

> Selection of specific fields using the syntax @field:hello world.

But it seems the second term is ignored? Whatever I put there, or omit it altogether, the result is only based on the first term (`hello`). Is there another syntax for this?

**Comment by itamarhaber** [comment]
Hello @mahemoff 

The second term shouldn't be ignored, but depending on your client (and especially in redis-cli) you'll need to put quotes (or ticks) around the query. Can you confirm that you're using quotes?

**Comment by mahemoff** [comment]
Thanks, yes I was trying it in redis-cli. It does work with quotes (`@field:"hello world"`). Not sure if that should be reflected in query syntax docs?

**Comment by mnunberg** [comment]
You’d need to quote it twice. First, you need to quote it for redis-cli so that it’s received as one argument and not two, and then you need to quote the actual “hello world” itself so that the search term itself is verbatim, and not simply searching for "@field:hello” “world”. Try to use FT.EXPLAINCLI (a variant of FT.EXPLAIN) and see what it thinks of your query.

**Comment by mnunberg** [comment]
The quotes are only intended for exact phrase matching. For an intersection, simply do something like
	@title:tech @title:ne*
or
	@title:(tech ne*)

the two forms are equivalent.

**Comment by mahemoff** [comment]
Brilliant. Everything makes sense now! I didn't realise the same field prefix could be repeated as I was imagining only one would be processed. Thanks.
