### ISSUE TITLE
Clean geo index on updates and not only on delete

### ISSUE THREAD

**Issue by MeirShpilraien** [RedisLabsModules/RediSearch#588]

**Comment by mnunberg** [comment]
Implementing this is non-trivial. The issue is that accessing the geo index is not exactly cheap, and we can't do this from within the indexer thread. If we could limit this to only documents which we know have geo indexes, it might help a bit -- however, we don't know what fields are contained by which documents unless we fetch the contents.

So, a solution would track whether or not the document has a geo field (and which geo fields-- we can have more than one), and then delete it from within the indexer thread (we need to hold the lock anyway... so why not...)
