### ISSUE TITLE
Two separate indexes affects each other

### ISSUE THREAD

**Issue by onexdrk** [RedisLabsModules/RediSearch#64]
create two absolutely separate indexed mixes1 & mixes2 and add two separate documents to each
```
FT.CREATE mixes1 SCHEMA name text
FT.CREATE mixes2 SCHEMA namename text
FT.ADD mixes1 doc10 1 FIELDS name name
FT.ADD mixes2 doc10 1 FIELDS namename name
```
notice, that doc10 in mixes1 not same as doc10 in mixes2
search document in `mixes1` by name, expect to get doc10 just with name field:

```
FT.SEARCH mixes1 "@name:name*"


2) "doc10"
3) 1) "name"
   2) "name"
   3) "namename"
   4) "name"
```

result mixed with `mixes2 ` index fields

**Comment by dvirsky** [comment]
What happens is this - the document is stored as is, in a hash key, and the key you give it is not altered. The document is disconnected from the index, and you can index the same document in two separate indexes if you want using FT.ADDHASH. This is not a bug but by design. It should be mentioned in the docs though.

**Comment by onexdrk** [comment]
Thanks!
