### ISSUE TITLE
Understanding how memory is handled for large data sets

### ISSUE THREAD

**Issue by garygreen** [RedisLabsModules/RediSearch#673]
We're looking to move away from Elastic Search to RediSearch, as es is a bit overkill for us and a real memory hog. Tried to find any information about how RediSearch handles memory for large data sets and I couldn't really find much information about how RediSearch internally stores/handles memory. All I could deciper was that it's basically in-memory. Does that mean if you index 5 million documents it'll have to have all of those in memory at once? Does it ever query from disk / swap if memory is getting low?

If there's any docs or info you can point to that would be much appreciated.

**Comment by mnunberg** [comment]
The indexes themselves are stored in memory. You can use redisearch in index-only mode, so that you can store your documents elsewhere, however. Otherwise, documents themselves are stored in memory as well.

Generally the memory usage of the index itself is extremely small, and the memory usage of the documents is whatever the contents of the documents may be, plus whatever metadata overhead Redis has for the documents. Redis Labs also has a [Redis On Flash](https://docs.redislabs.com/latest/rs/concepts/memory-architecture/redis-flash/) feature in its enterprise version which allows documents to be stored on flash memory on an LRU basis, as well.

As far as your use case is concerned, the actual memory usage for 5M documents depends entirely on the size of each document, what you're indexing, etc.
