### ISSUE TITLE
when the document will be delete?

### ISSUE THREAD

**Issue by AllenLi1990** [RedisLabsModules/RediSearch#78]
hi. I am using the version 0.16.0
"NOTE: This does not actually delete the document from the index, just marks it as deleted. Thus, deleting and re-inserting the same document over and over will inflate the index size with each re-insertion."
I want to know when the document will actually delete because my index size is very large large now.
Thanks~

**Comment by dvirsky** [comment]
Actually, FT.DEL does not delete the HASH object where the document is stored, because it might be indexed by another index. If you want to remove the actual document, just run:

```
FT.DEL {key}
DEL {key}
```

You can run it with MULTI/EXEC of course. 

Now, regarding the index memory - we have a garbage collector that frees up this stuff, but currently it doesn't run automatically. In the next version it will run automatically and the index will collect its garbage.

**Comment by AllenLi1990** [comment]
Thank you very much for the perfect solution to the problem！
By the way. I want feedback another question.
I run this command.
`
FT.CREATE myIdx SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT sc NUMERIC
FT.ADD myIdx doc1 1.0 FIELDS title "hello world" body "lorem ipsum" url "http://redis.io" sc 100
FT.DROP myIdx
KEYS *myIdx*
`
Turn out to be
`
1) "nm:myIdx/sc"
`
When I drop an index, it will not delete the NUMERIC data automatically.

**Comment by dvirsky** [comment]
@AllenLi1990 hmmm, that's another bug. could you please open a new issue about it? 
For now, just use FLUSHDB when dropping an index.

**Comment by tw-bert** [comment]
@dvirsky I recommend adding this (`If you want to remove the actual document`...) to the RediSearch command documentation
